name: task_management
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  lottie: ^3.3.1
  ftoast: ^2.0.0
  flutter_slider_drawer: ^3.0.2
  intl: ^0.19.0
  animate_do: ^4.2.0
  table_calendar: ^3.1.3
  flutter_localizations:
    sdk: flutter
  redis: ^4.0.0
  flutter_easyloading: ^3.0.5
  flutter_datetime_picker_plus: ^2.2.0
  http: ^1.3.0
  shared_preferences: ^2.2.2
  get: ^4.6.6
  flutter_sticky_header: ^0.7.0
  percent_indicator: ^4.2.3
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app-icon14.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/lotties/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
